### PR TITLE
fix: remove "npm root" command

### PR DESCRIPTION
**Pull request by aleclarson**
Unless I am missing something important, the "npm root" command (without -g) always prints the nearest "node_modules" directory, which is already covered when searching every parent directory.

I also moved the command into a new `getDefaultGlobalRoot` function so we can avoid spawning a child process when `process.env.NODE_PATH` is truthy.

### CODE REVIEW

**Comment by aleclarson** [comment]
Also, I would highly recommend using `lint-staged` to run `prettier --write` on commit.

**Comment by mateodelnorte** [comment]
I'm not against `prettier --write`. Wanna add it to this PR?

**Comment by aleclarson** [comment]
And I wouldn't mind memoizing the result of `npm root -g`.

**Comment by mateodelnorte** [comment]
As it stands now, you're never going to call that function more than once per run of the process. So, we probably don't need to refactor that yet.

**Comment by mateodelnorte** [comment]
Lemme know if you wanna update linting here. Otherwise, I'll merge away.

**Comment by aleclarson** [comment]
Yeah, I'm working on that.

**Comment by aleclarson** [comment]
Is there a bot that can update lockfiles for us?

**Comment by aleclarson** [comment]
Alright, I added `husky` and `lint-staged`. Tested it out, and it works perfect.

**Comment by mateodelnorte** [comment]
I think renovate updates lockfiles. We'll have to watch and see what it gets up to.

**Comment by aleclarson** [comment]
I just force-pushed to remove the lockfile updates in my commit.

**Comment by mateodelnorte** [comment]
woot

**Pull request merged**
