### PR TITLE
fix: add debug logs for unresolvable plugins

### PR DESCRIPTION
**Pull request by aleclarson**
This moves the `isImportable` function into `registerPlugin` where it belongs. This lets us warn users (via `debug` log) when a plugin is missing its main module.

Also, the `lib/isPlugin.js` module is no longer necessary.

Lastly, add a test for the undefined `$NODE_PATH` edge case.

### CODE REVIEW

**Comment by aleclarson** [comment]
@mateodelnorte Nope. That check is now in `registerPlugin`.

I edited the OP yesterday with:

> This moves the isImportable function into registerPlugin where it belongs. This lets us warn users (via debug log) when a plugin is missing its main module.

**Comment by aleclarson** [comment]
Maybe worth just letting `registerPlugin` throw instead of catching and printing to the debug log.

**Comment by mateodelnorte** [comment]
There's always the potential that somebody names a node_modules `meta-something-or-other` and it's not actually a meta plugin. :P

**Comment by aleclarson** [comment]
@mateodelnorte Alright, good point. LGTM!

**Comment by aleclarson** [comment]
Actually, that point is irrelevant, because the chances are practically none that you have a `meta-` package that (1) isn't a Meta plugin __and__ (2) has no entry module (which is what the `require.resolve` check protects against)

**Comment by mateodelnorte** [comment]
s'merged!

**Pull request merged**
