### PR TITLE
Add meta-config plugin

### PR DESCRIPTION
**Pull request by dorner**
This plugin allows you to use `meta config key value` to save configuration to the meta file so that other plugins can use this. First one I want to update is `get-meta-file`.

You can fork the repo and change the URL to your own if you think it will be easier to manage.

### CODE REVIEW

**Comment by mateodelnorte** [comment]
Looks like this isn't published on npm. Can you publish to a package name and update? 

Looks like there's a name collision with this package: https://www.npmjs.com/package/meta-config It might be unused and idle. You can email the maintainer (by looking in the git log for his email address), or npm support and see if you can get the name.

**Comment by dorner** [comment]
@mateodelnorte the package name has been changed to meta-configure. Please take another look!

**Comment by mateodelnorte** [comment]
Heyo! @dorner Couple of quick notes. Your package.json has an error in it, in the github url property: https://github.com/dorner/meta-configure/blob/master/package.json#L27. It's got an extra m in it, causing the link from npm to not go to the right github page. 

As for the plugin – can you update it so that `meta config` shows a list of commands, including get and set? I was thinking the plugin would contain the following commands:

- `meta config`
- `meta config get [key]`
- `meta config set [key] [value]`

We can start with those, for now, where you can set key value pairs and it will populate them under the config property of the .meta file. After that, we can think of adding things like `meta config get all`.

Thoughts?

**Comment by dorner** [comment]
@mateodelnorte sure, I'll update the current repo first. Thanks!

**Comment by mateodelnorte** [comment]
Sweet! We're planning to move to an org shortly, so meta-configure will end up there as well! https://github.com/mateodelnorte/meta/issues/91

**Comment by dorner** [comment]
Hmm - re your suggestion about `get` and `set` - I'd rather make it less wordy. If you just provide a single value, that would be the equivalent of a `get`, while two values would indicate a `set`. This is similar to how e.g. `bundle config` works.

**Comment by mateodelnorte** [comment]
I'm cool with that. 

In regards to an overall pattern, I think the following is sensible: 

```.meta file:
{
  projects: {},
  config: { 
    "top": "level",
    "items": "items",
    "are": "global"
    "or": "for meta, itself"
    "configure.item": "is a property the configure plugin cares about",
    "npm.item": "is a property the npm plugin cares about"
  }
}
```

Thoughts?

**Comment by dorner** [comment]
Looks good to me! I'm cool with replacing `options` with `config`, and the way you have it set up makes sense.

There's actually a plugin I'm working on (meta-sync) that will require a JSON object in there. I don't think we need to expose all of that in the CLI tool though - people can always just edit `.meta` themselves. :)

As for a `get all`, I can have `meta config` just print out all config values.

**Comment by mateodelnorte** [comment]
What's the data for meta-sync going to be used to do? I don't think people should edit .meta locally, unless they're creating something they want to push to a remote. This brings up the issue of where user-specific data should be stored. 

One thing to note is that meta is already set up to grab a `modules.exports = {}` style meta file ([via require](https://github.com/mateodelnorte/get-meta-file/blob/master/index.js#L60)). You could potentially satisfy what you need with env vars. But, we may want to adopt a separate file which isn't committed to git.

**Comment by dorner** [comment]
Yeah - in this case it would be a definition of files that should be synced across repos. E.g. if you have 3 repos but they should all share the same model or schema files. The plugin would basically read the configuration in .meta to determine which files should go where when `meta sync` is called. So it wouldn't be user-specific.

**Comment by dorner** [comment]
But that's a good point - my other PR (https://github.com/mateodelnorte/get-meta-file/pull/2) is indeed a user-specific setting. We should have a way of separating the two. 🤔

**Comment by dorner** [comment]
How about this? Something like `meta project-config` which would set project-level settings, and `meta config` which would set user-level settings in a file like `.meta-config` which should be .gitignored?

**Comment by dorner** [comment]
Hm. For now I don't actually have a use case for non-user settings other than my `meta sync` plugin, which as I said would require .meta to be edited manually anyway. I think we can just switch this over to using a `.meta-config` file and leave the project settings as something the plugins would need to define themselves.

**Comment by mateodelnorte** [comment]
I'd rather provide a framework for plugins to be able to put their settings in a single easily navigable location, with an easy to understand format. I think https://github.com/mateodelnorte/meta/pull/49#issuecomment-450208421 is what we want. And set and get is pretty much all you need to make that happen. 

Users shouldn't have to update a .meta file or a .config file in order to have some data specific to them. That will just lead to lots of accidental commits that shouldn't have happened.

**Comment by dorner** [comment]
@mateodelnorte Yep, I agree - which is why I said that user settings should live in a `.meta-config` file. We can't merge it together with the existing .meta file because that file needs to be checked into the repo, so by definition it can't be user-specific. So basically we repurpose this package to represent user settings which wouldn't be checked in.

I guess an ideal situation would be requiring plugins to define their settings, and each setting could be defined as a project or user setting. Then when `meta config` is called, it would put project settings into the main `.meta` file and user settings into `.meta-config`. This would require us creating a new registration method that plugins would have to implement, though.

My main issue is that right now I no longer have a use case for this entire idea. I can continue to implement if you think it's helpful, but I'm not invested any more and I'm not a fan of implementing something for which no one has a use yet.

**Comment by Jcbobo** [comment]
allow the possiblity (other pr are required) for plugin to be customized:

- store default value for command options 

- create "persistent" child repo groups to work on ( developer work maily on subset of child repo)  allowing create a branch on only that subset of child for example

**Comment by patrickleet** [comment]
@Jcbobo 

For:
> create "persistent" child repo groups to work on ( developer work maily on subset of child repo) allowing create a branch on only that subset of child for example

Sounds like you may just want meta repos in meta repos - I do this.

**Comment by Jcbobo** [comment]
small tasks, always same devs  make not  worth to have other two dedicated
repo keep references, non really a need bug the first thinks come to my
mind far user-level settings ( simplify devs day by day activities)

Il giorno Mer 2 Gen 2019, 20:38 Patrick Scott <notifications@github.com> ha
scritto:

**Comment by patrickleet** [comment]
Matt and I have been discussing a `tags` plugin or adding it to `meta project` that would probably behave similarly to this config plugin as well to make groups of repos.

**Pull request closed without merging**
